### ISSUE TITLE
include author names and dates?

### ISSUE THREAD

**Issue by neilsmind** [rajasegar/awesome-micro-frontends#2]
First, thank you for starting this list. Given that many of the items have similar titles (and that micro-frontends is likely to grow as a topic), would it make sense to start adding publishing date (if known) and author or source to the links? Here's an example related to the PR I just submitted:

> - [Micro Front-Ends: Webpack Manifest](https://medium.embengineering.com/micro-front-ends-webpack-manifest-b05fc63a0d53) - [Emmanuel Morales](https://medium.embengineering.com/@embengineering) (Mar 21, 2018)

I'd be happy to help run down the sources / dates for the existing links

**Comment by rajasegar** [comment]
Thanks @neilsmind much appreciated
