### ISSUE TITLE
I made a new javascript framework with micro-frontends support.

### ISSUE THREAD

**Issue by afsec** [rajasegar/awesome-micro-frontends#21]
A Javascript framework implementation of "UI Focused State Oriented Architecture" grounded by MVP (Model View Presenter), with micro-frontends support.

Project: https://github.com/afsec/cellular-js
Sample WebApp: https://github.com/afsec/cellular-js-example-app

@naltatis aproval: https://github.com/neuland/micro-frontends/issues/32

**Comment by marconi1992** [comment]
Hi @afsec, kudos for your contributions in the Microfrontends community!! I liked the Model View Presenter pattern, we're using it in Ara Framework as well.

**Comment by marconi1992** [comment]
@afsec  we added your framework in the list.
