### ISSUE TITLE
Single SPA Slack channel is broken

### ISSUE THREAD

**Issue by codesandtags** [rajasegar/awesome-micro-frontends#33]
In the documentation the Single SPA slack channel is broken: 

https://single-spa.slack.com/join/shared_invite/enQtMzIwMTcxNTU3ODQyLTM1Y2U1OWMzNTNjOWYyZDBlMDJhN2VkYzk3MDI2NzQ2Nzg0MzMzNjVhNWE2YjVhMTcxNjFkOWYzMjllMmUxMjk

a) Should we generate a link per month?
b) Should we put the email from someone to generate invites?

**Comment by rajasegar** [comment]
@codesandtags TBH, I really don't know what would be the ideal solution, but I am ready to update the invite link here anytime it changes, if someone reports the same.

**Comment by codesandtags** [comment]
I think the best option is using the references of the main page https://single-spa.js.org/ , in that page there is consume directly to get invitation. :D
